dubbo:
  application:
    id: @pom.artifactId@
    name: @pom.artifactId@
  scan:
    base-packages: com.fanmu.muwu.service.provider.user.service.impl # Dubbo 服务实现类的扫描基准包
  config-center:
    address: zookeeper://172.16.34.85:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://172.16.34.85:2181
    timeout: 30000
  protocol:
    name: dubbo # 选用 dubbo 协议
    port: -1 # 协议端口, -1 表示从 20880 开始自增端口
  registry: # Dubbo 服务注册中心配置, 对应 RegistryConfig 类
    address: zookeeper://172.16.34.85:2181
    timeout: 30000
  provider: # Dubbo 服务端配置
    cluster: failfast # 集群方式,可选: failover/failfast/failsafe/failback/forking
    retries: 0 # 远程服务调用重试次数, 不包括第一次调用, 不需要重试请设为0
    timeout: 600000 # 远程服务调用超时时间(毫秒)
    token: true # 令牌验证, 为空表示不开启, 如果为true, 表示随机生成动态令牌
    dynamic: true # 服务是否动态注册, 如果设为false, 注册后将显示后disable状态, 需人工启用, 并且服务提供者停止时, 也不会自动取消册, 需人工禁用.
    delay: -1 # 延迟注册服务时间(毫秒)- , 设为-1时, 表示延迟到Spring容器初始化完成时暴露服务
    filter: platformdubbogetuserinfo, -exception # 服务提供方远程调用过程拦截器名称, 多个名称用逗号分隔
  consumer: # Dubbo 消费端配置
    check: false
    validation: true # 是否启用JSR303标准注解验证, 如果启用, 将对方法参数上的注解进行校验

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    #    url: jdbc:mysql://47.98.182.53:3306/mw_user_center?characterEncoding=utf8&useSSL=false
    #    url: jdbc:mysql://127.0.0.1:3306/mw_user_center?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://172.16.34.85:3306/mw_user_center?characterEncoding=utf8&useSSL=false
    username: fanmu
    password: Qwer+1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow: true
        login-username: admin
        login-password: admin
  redis:
    #    host: 47.98.182.53
    #    password: muwu
    host: 172.16.34.85
    port: 6379
    timeout: 90000
    database: 1
  elasticsearch:
    rest:
      uris:
        - 172.16.34.85:9200

mybatis-plus:
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

