server:
  port: 8090
  servlet:
    context-path: /muwu-auth

dubbo:
  application:
    id: @pom.artifactId@
    name: @pom.artifactId@
  scan:
    base-packages: com.fanmu.muwu.web.api.controller # Dubbo 服务实现类的扫描基准包
  config-center:
    address: zookeeper://172.16.34.85:2181
    timeout: 30000
  metadata-report:
    address: zookeeper://172.16.34.85:2181
    timeout: 30000
  registry: # Dubbo 服务注册中心配置, 对应 RegistryConfig 类
    address: zookeeper://172.16.34.85:2181
    timeout: 30000
  consumer: # Dubbo 消费端配置
    check: false

spring:
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    #    url: jdbc:mysql://47.98.182.53:3306/mw?characterEncoding=utf8&useSSL=false
    #    url: jdbc:mysql://127.0.0.1:3306/mw?characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://172.16.34.85:3306/mw_auth_center?characterEncoding=utf8&useSSL=false
    username: fanmu
    password: Qwer+1234
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 50
      min-idle: 50
      max-active: 100
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      stat-view-servlet:
        allow: true
        login-username: admin
        login-password: admin
  redis:
    #    host: 47.98.182.53
    #    password: muwu
    host: 172.16.34.85
    port: 6379
    timeout: 90000
    database: 0
  session:
    store-type: redis
    redis:
      namespace: muwu:session
  # 第三方联合登录
  security:
    oauth2:
      client:
        registration:
          weixin:
            provider: weixin
            clientName: weixin
            clientId: wx5469a88e5b5dea0c
            clientSecret: 1de1d876b023d6a5db6cac99bf9119d4
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: post
            redirectUri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
          qq:
            provider: qq
            clientName: qq
            clientId: 101780039
            clientSecret: fbd8fa62dc94a480d74142f34e00f308
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: post
            redirectUri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
        #            redirectUri: '{baseUrl}/qq/callback'
        provider:
          weixin:
            authorizationUri: https://open.weixin.qq.com/connect/qrconnect
            tokenUri: https://api.weixin.qq.com/sns/oauth2/access_token
            userInfoUri: https://api.weixin.qq.com/sns/userinfo
            userNameAttribute: openid
            userInfoAuthenticationMethod: form
          qq:
            authorizationUri: https://graph.qq.com/oauth2.0/authorize
            tokenUri: https://graph.qq.com/oauth2.0/token
            userInfoUri: https://graph.qq.com/user/get_user_info
            userNameAttribute: nickname
            userInfoAuthenticationMethod: form

security:
  oauth2:
    client:
      clientId: muwu-client-auth
      clientSecret: muwuClientSecret
      access-token-uri: http://127.0.0.1:8090/oauth/token
      user-authorization-uri: http://127.0.0.1:8090/oauth/authorize
    resource:
      user-info-uri: http://127.0.0.1:8090/muwu-auth/oauth/user
      #      jwt:
      #        key-uri: http://127.0.0.1:8090/muwu-auth/oauth/token_key
      token-info-uri: http://127.0.0.1:8090/muwu-auth/oauth/check_token

muwu:
  token:
    interceptor:
      enable: true
  security:
    social:
      filterProcessesUrl: /auth/social
      qq:
        app-id: 1109790134
        app-secret: ctfb87f778GwNKnm
        providerId: qq
      weixin:
        app-id: wxe714c1d1f061fc54
        app-secret: 3ec45ac52c83d21a4392f4a484afdd90
        providerId: weixin
    code:
      image:
        expireIn: 180
      #        url: /auth/registerUser,/auth/form,/submitResetPwdEmail,/code/sms
      sms:
        expireIn: 600
        url: /auth/submitResetPwdPhone
        mobileMaxSendCount: 1
        ipMaxSendCount: 2
        totalMaxSendCount: 3
    oauth2:
      tokenStore: redis #redis、jwt
      jwtSigningKey: muwu
      ignore:
        urls:
          - /auth/code/**
          - /oauth/login
          - /oauth/result
          - /auth/login
          - /auth/result
          - /error
          #          - /oauth/authorize
          #          - /auth/**
          #          - /login/**
          - /assets/**
#          - /social/**